# Generated by Django 6.0.2 on 2026-03-12 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reclamation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("lighting", "Éclairage Public"),
                            ("trash", "Déchets / Hygiène"),
                            ("roads", "Voirie / Routes"),
                            ("noise", "Nuisances Sonores"),
                            ("other", "Autre"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("in_progress", "En cours"),
                            ("resolved", "Résolue"),
                            ("rejected", "Rejetée"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="reclamations/",
                        verbose_name="Image / Preuve",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"user_type": "agent"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_reclamations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "citizen",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "citizen"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="my_reclamations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
