# Generated by Django 6.0.2 on 2026-03-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reclamations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reclamation",
            name="is_duplicate",
            field=models.BooleanField(default=False, verbose_name="Doublon détecté"),
        ),
        migrations.AddField(
            model_name="reclamation",
            name="latitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Latitude"),
        ),
        migrations.AddField(
            model_name="reclamation",
            name="longitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Longitude"),
        ),
        migrations.AddField(
            model_name="reclamation",
            name="priority",
            field=models.CharField(
                choices=[
                    ("faible", "Faible"),
                    ("normale", "Normale"),
                    ("urgente", "Urgente"),
                ],
                default="normale",
                max_length=10,
                verbose_name="Priorité",
            ),
        ),
        migrations.AddField(
            model_name="reclamation",
            name="service_responsable",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Service Responsable"
            ),
        ),
    ]
