# Generated by Django 6.0.2 on 2026-04-01 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0002_reclamation_is_duplicate_reclamation_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='reclamations.reclamation', verbose_name='Doublon de'),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='similarity_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Score de similarité'),
        ),
    ]
