# Generated by Django 6.0.2 on 2026-03-24 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0002_add_location_pointfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='is_duplicate',
            field=models.BooleanField(default=False, verbose_name='Doublon détecté'),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='priority',
            field=models.CharField(choices=[('faible', 'Faible'), ('normale', 'Normale'), ('urgente', 'Urgente')], default='normale', max_length=10, verbose_name='Priorité'),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='service_responsable',
            field=models.CharField(blank=True, max_length=100, verbose_name='Service Responsable'),
        ),
    ]
