# Generated by Django 6.0.2 on 2026-05-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0005_remove_limit_choices_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='category',
            field=models.CharField(choices=[('lighting', 'Éclairage Public'), ('trash', 'Déchets / Hygiène'), ('roads', 'Voirie / Routes'), ('noise', 'Nuisances Sonores'), ('water', 'Eau & Assainissement'), ('construction', 'Urbanisme & Construction'), ('social', 'Affaires Sociales'), ('commerce', 'Commerces & Marchés'), ('taxes', 'Finances & Impôts'), ('other', 'Autre')], default='other', max_length=20, verbose_name='Catégorie'),
        ),
    ]
