# Generated by Django 6.0.2 on 2026-05-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_articleimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Image de couverture (URL ou Base64)",
            ),
        ),
    ]
