# Generated by Django 6.0.2 on 2026-05-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_alter_article_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articleimage",
            name="image",
            field=models.TextField(verbose_name="Image supplémentaire (URL ou Base64)"),
        ),
    ]
