# Generated by Django 6.0.2 on 2026-04-03 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeConstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse_terrain', models.CharField(max_length=300)),
                ('numero_parcelle', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('type_travaux', models.CharField(choices=[('construction_neuve', 'Construction neuve'), ('renovation', 'Rénovation'), ('extension', 'Extension'), ('demolition', 'Démolition'), ('cloture', 'Clôture'), ('piscine', 'Piscine'), ('panneau_solaire', 'Panneaux solaires'), ('ravalement', 'Ravalement de façade'), ('autre', 'Autre')], max_length=50)),
                ('type_travaux_libre', models.CharField(blank=True, max_length=200)),
                ('usage_batiment', models.CharField(choices=[('habitation', 'Habitation'), ('commercial', 'Commercial'), ('industriel', 'Industriel'), ('agricole', 'Agricole'), ('mixte', 'Mixte')], default='habitation', max_length=50)),
                ('description_travaux', models.TextField()),
                ('surface_terrain', models.FloatField(blank=True, help_text='m²', null=True)),
                ('surface_construite', models.FloatField(blank=True, help_text='m²', null=True)),
                ('nombre_etages', models.IntegerField(default=1)),
                ('hauteur_max', models.FloatField(blank=True, help_text='mètres', null=True)),
                ('date_debut_prevue', models.DateField(blank=True, null=True)),
                ('duree_travaux_mois', models.IntegerField(blank=True, null=True)),
                ('cout_estime', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('nom_entrepreneur', models.CharField(blank=True, max_length=200)),
                ('telephone_entrepreneur', models.CharField(blank=True, max_length=20)),
                ('nom_proprietaire', models.CharField(max_length=200)),
                ('cin_proprietaire', models.CharField(blank=True, max_length=20)),
                ('telephone_proprietaire', models.CharField(blank=True, max_length=20)),
                ('titre_foncier', models.FileField(blank=True, null=True, upload_to='construction/titres/')),
                ('plan_architectural', models.FileField(blank=True, null=True, upload_to='construction/plans/')),
                ('photo_terrain', models.ImageField(blank=True, null=True, upload_to='construction/photos/')),
                ('devis_estimatif', models.FileField(blank=True, null=True, upload_to='construction/devis/')),
                ('cin_proprietaire_recto', models.ImageField(blank=True, null=True, upload_to='construction/cin/')),
                ('cin_proprietaire_verso', models.ImageField(blank=True, null=True, upload_to='construction/cin/')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('en_cours_instruction', "En cours d'instruction"), ('favorable', 'Avis favorable'), ('defavorable', 'Avis défavorable'), ('changes_requested', 'Modifications demandées'), ('permis_delivre', 'Permis délivré'), ('rejet_definitif', 'Rejet définitif')], default='pending', max_length=30)),
                ('priorite', models.CharField(choices=[('normale', 'Normale'), ('haute', 'Haute'), ('urgente', 'Urgente')], default='normale', max_length=20)),
                ('commentaire_agent', models.TextField(blank=True)),
                ('permis_signe', models.FileField(blank=True, null=True, upload_to='construction/permis/')),
                ('is_paid', models.BooleanField(default=False)),
                ('is_high_risk', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_construction', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de construction',
                'verbose_name_plural': 'Demandes de construction',
                'ordering': ['-created_at'],
            },
        ),
    ]
