# Generated by Django 6.0.2 on 2026-04-04 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maison_construction', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeCertificatVocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prenom', models.CharField(max_length=200)),
                ('cin', models.CharField(max_length=8)),
                ('adresse_bien', models.CharField(max_length=300)),
                ('cin_copie', models.ImageField(blank=True, null=True, upload_to='vocation/cin/')),
                ('quitus', models.FileField(blank=True, null=True, upload_to='vocation/quitus/')),
                ('certificat_propriete', models.FileField(blank=True, null=True, upload_to='vocation/propriete/')),
                ('plan_cadastral', models.FileField(blank=True, null=True, upload_to='vocation/cadastral/')),
                ('plan_situation', models.FileField(blank=True, null=True, upload_to='vocation/situation/')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('en_cours', 'En cours de traitement'), ('delivre', 'Certificat délivré'), ('rejete', 'Rejeté')], default='pending', max_length=20)),
                ('commentaire_agent', models.TextField(blank=True)),
                ('certificat_signe', models.FileField(blank=True, null=True, upload_to='vocation/delivre/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_certificat_vocation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de certificat de vocation',
                'verbose_name_plural': 'Demandes de certificat de vocation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DemandeGoudronnage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prenom', models.CharField(max_length=200)),
                ('cin', models.CharField(max_length=8)),
                ('adresse_residence', models.CharField(max_length=300)),
                ('localisation_rue', models.TextField(help_text='Description de la rue concernée')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('cin_copie', models.ImageField(blank=True, null=True, upload_to='goudronnage/cin/')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('en_cours', 'En cours de traitement'), ('traite', 'Traité'), ('rejete', 'Rejeté')], default='pending', max_length=20)),
                ('commentaire_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_goudronnage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de goudronnage',
                'verbose_name_plural': 'Demandes de goudronnage',
                'ordering': ['-created_at'],
            },
        ),
    ]
