# Generated by Django 6.0.2 on 2026-04-05 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maison_construction", "0002_demandecertificatvocation_demandegoudronnage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DemandeRaccordement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_reseau",
                    models.CharField(
                        choices=[
                            ("eau", "Eau (SONEDE)"),
                            ("electricite", "Électricité (STEG)"),
                            ("assainissement", "Assainissement (ONAS)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("adresse_raccordement", models.CharField(max_length=300)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "cin_copie",
                    models.FileField(
                        blank=True, null=True, upload_to="raccordement/cin/"
                    ),
                ),
                (
                    "titre_propriete",
                    models.FileField(
                        blank=True, null=True, upload_to="raccordement/propriete/"
                    ),
                ),
                (
                    "permis_batir",
                    models.FileField(
                        blank=True, null=True, upload_to="raccordement/permis/"
                    ),
                ),
                (
                    "plan_situation",
                    models.FileField(
                        blank=True, null=True, upload_to="raccordement/situation/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("visite_programmee", "Visite programmée"),
                            ("devis_envoye", "Devis envoyé"),
                            ("paye", "Devis payé"),
                            ("termine", "Terminé / Branché"),
                            ("rejete", "Rejeté"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                (
                    "devis_montant",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "devis_pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="raccordement/devis/"
                    ),
                ),
                ("date_visite", models.DateTimeField(blank=True, null=True)),
                ("commentaire_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "citizen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demandes_raccordement",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande de raccordement",
                "verbose_name_plural": "Demandes de raccordement",
                "ordering": ["-created_at"],
            },
        ),
    ]
