# Generated by Django 6.0.2 on 2026-04-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maison_construction", "0003_demanderaccordement"),
    ]

    operations = [
        migrations.AddField(
            model_name="demandecertificatvocation",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="demandecertificatvocation",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="demandegoudronnage",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="demandegoudronnage",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="demanderaccordement",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="demanderaccordement",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
