# Generated by Django 6.0.2 on 2026-04-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maison_construction", "0004_demandecertificatvocation_is_paid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="demandeconstruction",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
