# Generated by Django 6.0.2 on 2026-03-20 16:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("extrait_naissance", "0002_extraitnaissance_uuid"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtraitDeces",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("annee_acte", models.IntegerField(verbose_name="Année de l'acte")),
                (
                    "numero_registre",
                    models.CharField(max_length=50, verbose_name="N° Registre"),
                ),
                (
                    "date_deces",
                    models.DateTimeField(verbose_name="Date et heure du décès"),
                ),
                (
                    "lieu_deces_ar",
                    models.CharField(max_length=200, verbose_name="Lieu du décès AR"),
                ),
                (
                    "lieu_deces_fr",
                    models.CharField(max_length=200, verbose_name="Lieu du décès FR"),
                ),
                (
                    "declarant_ar",
                    models.CharField(max_length=200, verbose_name="Déclarant AR"),
                ),
                (
                    "declarant_fr",
                    models.CharField(max_length=200, verbose_name="Déclarant FR"),
                ),
                (
                    "gouvernorat_ar",
                    models.CharField(
                        default="نابل", max_length=100, verbose_name="Gouvernorat AR"
                    ),
                ),
                (
                    "gouvernorat_fr",
                    models.CharField(
                        default="Nabeul", max_length=100, verbose_name="Gouvernorat FR"
                    ),
                ),
                (
                    "commune_ar",
                    models.CharField(
                        default="قليبية", max_length=100, verbose_name="Commune AR"
                    ),
                ),
                (
                    "commune_fr",
                    models.CharField(
                        default="Kelibia", max_length=100, verbose_name="Commune FR"
                    ),
                ),
                (
                    "officer_etat_civil_ar",
                    models.CharField(
                        default="",
                        max_length=200,
                        verbose_name="Officier État Civil AR",
                    ),
                ),
                (
                    "officer_etat_civil_fr",
                    models.CharField(
                        default="",
                        max_length=200,
                        verbose_name="Officier État Civil FR",
                    ),
                ),
                (
                    "numero_ordre",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Numéro d'ordre",
                    ),
                ),
                (
                    "prix",
                    models.DecimalField(
                        decimal_places=3, default=0.5, max_digits=6, verbose_name="Prix"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "defunt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extraits_deces",
                        to="extrait_naissance.citoyen",
                        verbose_name="Défunt",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="extraits_deces",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur du portail",
                    ),
                ),
            ],
            options={
                "verbose_name": "Extrait de Décès",
                "verbose_name_plural": "Extraits de Décès",
                "ordering": ["-annee_acte", "-created_at"],
            },
        ),
    ]
