# Generated by Django 6.0.2 on 2026-03-20 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extrait_deces", "0001_initial"),
        ("extrait_naissance", "0002_extraitnaissance_uuid"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="extraitdeces",
            options={},
        ),
        migrations.CreateModel(
            name="DeclarationDeces",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_deces",
                    models.DateTimeField(verbose_name="Date et heure du décès"),
                ),
                (
                    "lieu_deces_ar",
                    models.CharField(max_length=200, verbose_name="Lieu du décès AR"),
                ),
                (
                    "lieu_deces_fr",
                    models.CharField(max_length=200, verbose_name="Lieu du décès FR"),
                ),
                (
                    "commentaire",
                    models.TextField(blank=True, verbose_name="Commentaire / ملاحظات"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente / قيد الانتظار"),
                            ("validated", "Validé / تم التحقق"),
                            ("rejected", "Rejeté / مرفوض"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "declarant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="declarations_deces",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Déclarant",
                    ),
                ),
                (
                    "defunt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="declarations_deces",
                        to="extrait_naissance.citoyen",
                        verbose_name="Défunt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Déclaration de Décès",
                "verbose_name_plural": "Déclarations de Décès",
            },
        ),
    ]
