# Generated by Django 6.0.2 on 2026-03-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extrait_deces", "0002_alter_extraitdeces_options_declarationdeces"),
    ]

    operations = [
        migrations.AddField(
            model_name="declarationdeces",
            name="police_report",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="declarations/deces/police/",
                verbose_name="Rapport de police (si suspect)",
            ),
        ),
    ]
