# Generated by Django 6.0.2 on 2026-03-27 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extrait_deces", "0003_declarationdeces_police_report"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DemandeInhumation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cimetiere_ar",
                    models.CharField(
                        default="مقبرة قليبية",
                        max_length=200,
                        verbose_name="Cimetière (AR)",
                    ),
                ),
                (
                    "cimetiere_fr",
                    models.CharField(
                        default="Cimetière de Kelibia",
                        max_length=200,
                        verbose_name="Cimetière (FR)",
                    ),
                ),
                (
                    "date_souhaitee",
                    models.DateTimeField(
                        verbose_name="Date et heure souhaitées d'inhumation"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente / قيد الانتظار"),
                            ("approved", "Approuvée / تمت الموافقة"),
                            ("rejected", "Refusée / مرفوضة"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "citizen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demandes_inhumation",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Demandeur",
                    ),
                ),
                (
                    "declaration_deces",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demande_inhumation",
                        to="extrait_deces.declarationdeces",
                        verbose_name="Déclaration de décès associée",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande d'inhumation",
                "verbose_name_plural": "Demandes d'inhumation",
            },
        ),
    ]
