# Generated by Django 6.0.2 on 2026-04-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extrait_deces", "0004_demandeinhumation"),
    ]

    operations = [
        migrations.AddField(
            model_name="declarationdeces",
            name="is_paid",
            field=models.BooleanField(default=False, verbose_name="Payé"),
        ),
        migrations.AddField(
            model_name="declarationdeces",
            name="paid_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date du paiement"
            ),
        ),
        migrations.AddField(
            model_name="extraitdeces",
            name="is_paid",
            field=models.BooleanField(default=False, verbose_name="Payé"),
        ),
        migrations.AddField(
            model_name="extraitdeces",
            name="paid_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date du paiement"
            ),
        ),
    ]
