# Generated by Django 6.0.2 on 2026-04-22 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "extrait_deces",
            "0005_declarationdeces_is_paid_declarationdeces_paid_at_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DemandeTransfertCorps",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom_defunt",
                    models.CharField(max_length=200, verbose_name="Nom du défunt"),
                ),
                ("date_deces", models.DateField(verbose_name="Date de décès")),
                (
                    "lieu_deces",
                    models.CharField(max_length=200, verbose_name="Lieu de décès"),
                ),
                (
                    "lieu_inhumation",
                    models.CharField(
                        max_length=200, verbose_name="Destination d'inhumation"
                    ),
                ),
                (
                    "certificat_medical",
                    models.FileField(
                        upload_to="declarations/transfert/medical/",
                        verbose_name="Certificat médical",
                    ),
                ),
                (
                    "cin_defunt",
                    models.FileField(
                        upload_to="declarations/transfert/cin/",
                        verbose_name="CIN du défunt",
                    ),
                ),
                ("is_paid", models.BooleanField(default=False, verbose_name="Payé")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente / قيد الانتظار"),
                            ("approved", "Approuvée / تمت الموافقة"),
                            ("rejected", "Refusée / مرفوضة"),
                            ("ready", "Prêt / جاهز"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "citizen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demandes_transfert",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Demandeur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande de transfert de corps",
                "verbose_name_plural": "Demandes de transfert de corps",
            },
        ),
    ]
