# Generated by Django 6.0.2 on 2026-04-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extrait_deces", "0006_demandetransfertcorps"),
    ]

    operations = [
        migrations.AddField(
            model_name="demandetransfertcorps",
            name="date_transfert",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date prévue du transfert"
            ),
        ),
    ]
