# Generated by Django 6.0.2 on 2026-02-22 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_fr", models.CharField(max_length=100, verbose_name="Nom (FR)")),
                ("name_ar", models.CharField(max_length=100, verbose_name="Nom (AR)")),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="FontAwesome icon class", max_length=50
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_fr",
                    models.CharField(
                        max_length=200, verbose_name="Nom du service (FR)"
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(
                        max_length=200, verbose_name="Nom du service (AR)"
                    ),
                ),
                (
                    "description_fr",
                    models.TextField(blank=True, verbose_name="Description (FR)"),
                ),
                (
                    "description_ar",
                    models.TextField(blank=True, verbose_name="Description (AR)"),
                ),
                (
                    "processing_time",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Délai de traitement"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="services.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Requirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_fr",
                    models.CharField(
                        max_length=200, verbose_name="Document requis (FR)"
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(
                        max_length=200, verbose_name="Document requis (AR)"
                    ),
                ),
                ("is_mandatory", models.BooleanField(default=True)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirements",
                        to="services.service",
                    ),
                ),
            ],
        ),
    ]
