# Generated by Django 6.0.2 on 2026-03-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="form_pdf",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="service_forms/",
                verbose_name="Formulaire PDF",
            ),
        ),
    ]
