# Generated by Django 6.0.2 on 2026-03-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_service_form_pdf"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="form_pdf",
        ),
        migrations.AddField(
            model_name="service",
            name="form_pdf_ar",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="service_forms/ar/",
                verbose_name="Formulaire PDF (AR)",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="form_pdf_fr",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="service_forms/fr/",
                verbose_name="Formulaire PDF (FR)",
            ),
        ),
    ]
