# Generated by Django 6.0.2 on 2026-04-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_remove_service_form_pdf_service_form_pdf_ar_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="processing_time",
        ),
        migrations.AddField(
            model_name="service",
            name="processing_time_ar",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Délai de traitement (AR)"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="processing_time_fr",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Délai de traitement (FR)"
            ),
        ),
    ]
