# Generated by Django 6.0.2 on 2026-03-26 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("voirie", "Voirie"),
                            ("eclairage", "Éclairage public"),
                            ("dechets", "Déchets et propreté"),
                            ("eau", "Eau et assainissement"),
                            ("espaces_verts", "Espaces verts"),
                            ("batiments", "Bâtiments publics"),
                            ("autre", "Autre"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("en_cours", "En cours"),
                            ("resolu", "Résolu"),
                            ("resolu_avec_retard", "Résolu avec retard"),
                            ("en_retard", "En retard"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("faible", "Faible"),
                            ("normale", "Normale"),
                            ("urgente", "Urgente"),
                        ],
                        default="normale",
                        max_length=10,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="complaints/"),
                ),
                (
                    "latitude",
                    models.FloatField(default=36.8481, verbose_name="Latitude"),
                ),
                (
                    "longitude",
                    models.FloatField(default=11.0939, verbose_name="Longitude"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_duplicate", models.BooleanField(default=False)),
                (
                    "citizen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="complaints",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
