# Generated by Django 6.0.2 on 2026-03-12 05:46

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('voirie', 'Voirie'), ('eclairage', 'Éclairage public'), ('dechets', 'Déchets et propreté'), ('eau', 'Eau et assainissement'), ('espaces_verts', 'Espaces verts'), ('batiments', 'Bâtiments publics'), ('autre', 'Autre')], max_length=50)),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('resolu', 'Résolu'), ('resolu_avec_retard', 'Résolu avec retard'), ('en_retard', 'En retard')], default='en_attente', max_length=20)),
                ('priority', models.CharField(choices=[('faible', 'Faible'), ('normale', 'Normale'), ('urgente', 'Urgente')], default='normale', max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='complaints/')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_duplicate', models.BooleanField(default=False)),
            ],
        ),
    ]
