# Generated by Django 6.0.2 on 2026-02-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="neighborhood",
        ),
        migrations.AddField(
            model_name="customuser",
            name="city",
            field=models.CharField(
                default="Kelibia", max_length=100, verbose_name="Ville"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="governorate",
            field=models.CharField(
                choices=[
                    ("Ariana", "Ariana"),
                    ("Beja", "Béja"),
                    ("Ben Arous", "Ben Arous"),
                    ("Bizerte", "Bizerte"),
                    ("Gabes", "Gabès"),
                    ("Gafsa", "Gafsa"),
                    ("Jendouba", "Jendouba"),
                    ("Kairouan", "Kairouan"),
                    ("Kasserine", "Kasserine"),
                    ("Kebili", "Kébili"),
                    ("Kef", "Le Kef"),
                    ("Mahdia", "Mahdia"),
                    ("Manouba", "La Manouba"),
                    ("Medenine", "Médenine"),
                    ("Monastir", "Monastir"),
                    ("Nabeul", "Nabeul"),
                    ("Sfax", "Sfax"),
                    ("Sidi Bouzid", "Sidi Bouzid"),
                    ("Siliana", "Siliana"),
                    ("Sousse", "Sousse"),
                    ("Tataouine", "Tataouine"),
                    ("Tozeur", "Tozeur"),
                    ("Tunis", "Tunis"),
                    ("Zaghouan", "Zaghouan"),
                ],
                default="Nabeul",
                max_length=50,
                verbose_name="Gouvernorat",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="Est vérifié"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="otp_code",
            field=models.CharField(
                blank=True, max_length=6, null=True, verbose_name="Code OTP"
            ),
        ),
    ]
