# Generated by Django 6.0.2 on 2026-02-19 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_customuser_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="otp_code",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="validation_method",
        ),
    ]
