# Generated by Django 6.0.2 on 2026-02-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_customuser_otp_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[("citizen", "Citoyen"), ("agent", "Agent Municipal")],
                default="citizen",
                max_length=10,
                verbose_name="Type d'utilisateur",
            ),
        ),
    ]
