# Generated by Django 6.0.2 on 2026-03-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_customuser_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="cin_back_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="cin_images/",
                verbose_name="CIN Face Arrière",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="cin_front_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="cin_images/",
                verbose_name="CIN Face Avant",
            ),
        ),
    ]
