# Generated by Django 6.0.2 on 2026-03-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_customuser_cin_back_image_customuser_cin_front_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="first_name_ar",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Prénom (Arabe)"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="last_name_ar",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Nom (Arabe)"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("citizen", "Citoyen"),
                    ("agent", "Agent Municipal"),
                    ("supervisor", "Superviseur"),
                ],
                default="citizen",
                max_length=10,
                verbose_name="Type d'utilisateur",
            ),
        ),
    ]
