# Generated by Django 6.0.2 on 2026-03-30 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_cin_back_image_customuser_cin_front_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('citizen', 'Citoyen'), ('agent', 'Agent Municipal'), ('supervisor', 'Superviseur')], default='citizen', max_length=10, verbose_name="Type d'utilisateur"),
        ),
    ]
