# Generated by Django 6.0.2 on 2026-03-30 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_customuser_user_type"),
        ("accounts", "0007_customuser_first_name_ar_customuser_last_name_ar_and_more"),
    ]

    operations = []
