# Generated by Django 6.0.2 on 2026-03-30 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_merge_20260330_1117"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_holder", models.CharField(max_length=200)),
                ("last_4", models.CharField(max_length=4)),
                ("expiry", models.CharField(max_length=5)),
                ("brand", models.CharField(default="Visa", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
