# Generated by Django 6.0.2 on 2026-03-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_savedcard"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="date_of_birth",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de naissance"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_married",
            field=models.BooleanField(default=False, verbose_name="Est marié(e)"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="place_of_birth",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Lieu de naissance"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="spouse_cin",
            field=models.CharField(
                blank=True, max_length=8, null=True, verbose_name="CIN du conjoint"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="spouse_first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Prénom du conjoint"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="spouse_last_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Nom du conjoint"
            ),
        ),
    ]
