# Generated by Django 6.0.2 on 2026-03-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_customuser_date_of_birth_customuser_is_married_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="place_of_birth",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Lieu de naissance"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="spouse_first_name",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Prénom du conjoint"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="spouse_last_name",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Nom du conjoint"
            ),
        ),
    ]
