# Generated by Django 6.0.2 on 2026-03-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_customuser_place_of_birth_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="cin_back_image",
            field=models.TextField(
                blank=True, null=True, verbose_name="CIN Face Arrière (Base64)"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="cin_front_image",
            field=models.TextField(
                blank=True, null=True, verbose_name="CIN Face Avant (Base64)"
            ),
        ),
    ]
