# Generated by Django 6.0.2 on 2026-03-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_alter_customuser_cin_back_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="city",
            field=models.CharField(
                default="Kelibia", max_length=255, verbose_name="Ville"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="first_name_ar",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Prénom (Arabe)"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name_ar",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Nom (Arabe)"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="spouse_cin",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="CIN du conjoint"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="spouse_first_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Prénom du conjoint"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="spouse_last_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Nom du conjoint"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("citizen", "Citoyen"),
                    ("agent", "Agent Municipal"),
                    ("supervisor", "Superviseur"),
                ],
                default="citizen",
                max_length=50,
                verbose_name="Type d'utilisateur",
            ),
        ),
    ]
