# Generated by Django 6.0.2 on 2026-03-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0013_alter_customuser_city_alter_customuser_first_name_ar_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="cin_back_utf",
            field=models.TextField(
                blank=True, null=True, verbose_name="CIN Back Base64 NEW"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="cin_front_utf",
            field=models.TextField(
                blank=True, null=True, verbose_name="CIN Front Base64 NEW"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="cin_back_image",
            field=models.TextField(
                blank=True, null=True, verbose_name="CIN Face Arrière (Base64 Old)"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="cin_front_image",
            field=models.TextField(
                blank=True, null=True, verbose_name="CIN Face Avant (Base64 Old)"
            ),
        ),
    ]
