# Generated by Django 6.0.2 on 2026-04-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_customuser_cin_back_utf_customuser_cin_front_utf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='asd_active',
            field=models.BooleanField(default=False, verbose_name='Abonnement ASD Actif'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='asd_expiration',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'expiration ASD"),
        ),
    ]
