# Generated by Django 6.0.2 on 2026-04-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_customuser_asd_active_customuser_asd_expiration"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(default="Kelibia Smart City", max_length=255),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        default="webmaster.commune-kelibia@topnet.tn", max_length=254
                    ),
                ),
                ("maintenance_mode", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuration Système",
                "verbose_name_plural": "Configuration Système",
            },
        ),
    ]
