# Generated by Django 6.0.2 on 2026-04-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_siteconfiguration"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="preferred_language",
            field=models.CharField(
                choices=[("fr", "Français"), ("ar", "العربية")],
                default="fr",
                max_length=5,
                verbose_name="Langue préférée",
            ),
        ),
    ]
