# Generated by Django 6.0.2 on 2026-05-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_add_preferred_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='assigned_service',
            field=models.CharField(blank=True, choices=[('lighting', 'Éclairage Public'), ('trash', 'Déchets / Hygiène'), ('roads', 'Voirie / Routes'), ('noise', 'Nuisances Sonores'), ('water', 'Eau & Assainissement'), ('construction', 'Urbanisme & Construction'), ('social', 'Affaires Sociales & Événements'), ('commerce', 'Commerces & Marchés'), ('taxes', 'Finances & Impôts'), ('civil_registry', 'État Civil'), ('residence', 'Attestations de Résidence'), ('forum_moderator', 'Modération du Forum'), ('news_editor', 'Rédaction des Actualités'), ('general', 'Service Technique Général')], max_length=50, null=True, verbose_name='Service assigné (agents uniquement)'),
        ),
    ]
