# Generated by Django 6.0.2 on 2026-05-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_customuser_assigned_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="activation_code",
            field=models.CharField(
                blank=True, max_length=6, null=True, verbose_name="Code d'activation"
            ),
        ),
    ]
