# Generated by Django 6.0.2 on 2026-03-19 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("extrait_naissance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtraitMariage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("annee_acte", models.IntegerField(verbose_name="Année de l'acte")),
                (
                    "numero_registre",
                    models.CharField(max_length=50, verbose_name="N° Registre"),
                ),
                (
                    "gouvernorat_ar",
                    models.CharField(
                        default="نابل", max_length=100, verbose_name="Gouvernorat AR"
                    ),
                ),
                (
                    "gouvernorat_fr",
                    models.CharField(
                        default="Nabeul", max_length=100, verbose_name="Gouvernorat FR"
                    ),
                ),
                (
                    "commune_ar",
                    models.CharField(
                        default="قليبية", max_length=100, verbose_name="Commune AR"
                    ),
                ),
                (
                    "commune_fr",
                    models.CharField(
                        default="Kelibia", max_length=100, verbose_name="Commune FR"
                    ),
                ),
                ("date_mariage", models.DateField(verbose_name="Date du mariage")),
                (
                    "date_mariage_lettres_ar",
                    models.CharField(max_length=255, verbose_name="Date en lettres AR"),
                ),
                (
                    "date_mariage_lettres_fr",
                    models.CharField(max_length=255, verbose_name="Date en lettres FR"),
                ),
                (
                    "lieu_mariage_ar",
                    models.CharField(
                        default="بلدية قليبية",
                        max_length=200,
                        verbose_name="Lieu du mariage AR",
                    ),
                ),
                (
                    "lieu_mariage_fr",
                    models.CharField(
                        default="Municipalité de Kelibia",
                        max_length=200,
                        verbose_name="Lieu du mariage FR",
                    ),
                ),
                (
                    "regime_matrimonial",
                    models.CharField(
                        choices=[
                            ("separation", "Séparation des biens / الفصل في الأملاك"),
                            (
                                "communaute",
                                "Communauté des biens / الاشتراك في الأملاك",
                            ),
                        ],
                        default="separation",
                        max_length=20,
                        verbose_name="Régime Matrimonial",
                    ),
                ),
                (
                    "observations_ar",
                    models.TextField(
                        blank=True, default="", verbose_name="Observations AR"
                    ),
                ),
                (
                    "observations_fr",
                    models.TextField(
                        blank=True, default="", verbose_name="Observations FR"
                    ),
                ),
                (
                    "officer_etat_civil_ar",
                    models.CharField(
                        default="",
                        max_length=200,
                        verbose_name="Officier État Civil AR",
                    ),
                ),
                (
                    "officer_etat_civil_fr",
                    models.CharField(
                        default="",
                        max_length=200,
                        verbose_name="Officier État Civil FR",
                    ),
                ),
                (
                    "numero_ordre",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Numéro d'ordre",
                    ),
                ),
                (
                    "prix",
                    models.DecimalField(
                        decimal_places=3, default=2.0, max_digits=6, verbose_name="Prix"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "epouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mariages_epouse",
                        to="extrait_naissance.citoyen",
                        verbose_name="Épouse",
                    ),
                ),
                (
                    "epoux",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mariages_epoux",
                        to="extrait_naissance.citoyen",
                        verbose_name="Époux",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="extraits_mariage",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur du portail",
                    ),
                ),
            ],
            options={
                "verbose_name": "Extrait de Mariage",
                "verbose_name_plural": "Extraits de Mariage",
                "ordering": ["-annee_acte", "-created_at"],
            },
        ),
    ]
