# Generated by Django 6.0.2 on 2026-03-27 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extrait_mariage", "0002_extraitmariage_uuid"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="extraitmariage",
            options={},
        ),
        migrations.CreateModel(
            name="DemandeMariage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom_epoux",
                    models.CharField(max_length=200, verbose_name="Nom de l'époux"),
                ),
                (
                    "cin_epoux",
                    models.CharField(max_length=8, verbose_name="CIN de l'époux"),
                ),
                (
                    "nom_epouse",
                    models.CharField(max_length=200, verbose_name="Nom de l'épouse"),
                ),
                (
                    "cin_epouse",
                    models.CharField(max_length=8, verbose_name="CIN de l'épouse"),
                ),
                (
                    "date_souhaitee",
                    models.DateField(verbose_name="Date de mariage souhaitée"),
                ),
                (
                    "regime_matrimonial",
                    models.CharField(
                        choices=[
                            ("separation", "Séparation des biens / الفصل في الأملاك"),
                            (
                                "communaute",
                                "Communauté des biens / الاشتراك في الأملاك",
                            ),
                        ],
                        default="separation",
                        max_length=20,
                        verbose_name="Régime Matrimonial",
                    ),
                ),
                (
                    "cin_recto_epoux",
                    models.ImageField(
                        upload_to="declarations/mariage/epoux/cin_recto/",
                        verbose_name="CIN Epoux Recto",
                    ),
                ),
                (
                    "cin_verso_epoux",
                    models.ImageField(
                        upload_to="declarations/mariage/epoux/cin_verso/",
                        verbose_name="CIN Epoux Verso",
                    ),
                ),
                (
                    "extrait_naissance_epoux",
                    models.FileField(
                        upload_to="declarations/mariage/epoux/naissance/",
                        verbose_name="Extrait Naissance Epoux",
                    ),
                ),
                (
                    "certificat_medical_epoux",
                    models.FileField(
                        upload_to="declarations/mariage/epoux/medical/",
                        verbose_name="Certificat Médical Epoux",
                    ),
                ),
                (
                    "cin_recto_epouse",
                    models.ImageField(
                        upload_to="declarations/mariage/epouse/cin_recto/",
                        verbose_name="CIN Epouse Recto",
                    ),
                ),
                (
                    "cin_verso_epouse",
                    models.ImageField(
                        upload_to="declarations/mariage/epouse/cin_verso/",
                        verbose_name="CIN Epouse Verso",
                    ),
                ),
                (
                    "extrait_naissance_epouse",
                    models.FileField(
                        upload_to="declarations/mariage/epouse/naissance/",
                        verbose_name="Extrait Naissance Epouse",
                    ),
                ),
                (
                    "certificat_medical_epouse",
                    models.FileField(
                        upload_to="declarations/mariage/epouse/medical/",
                        verbose_name="Certificat Médical Epouse",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente / قيد الانتظار"),
                            ("verified", "Documents Vérifiés / الوثائق مقبولة"),
                            ("rejected", "Rejetée / مرفوضة"),
                            ("signed", "Signée / وقع إبرام العقد"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "commentaire_agent",
                    models.TextField(blank=True, verbose_name="Commentaire de l'agent"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "citizen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demandes_mariage",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande d'acte de Mariage",
                "verbose_name_plural": "Demandes d'actes de Mariage",
                "ordering": ["-created_at"],
            },
        ),
    ]
