# Generated by Django 6.0.2 on 2026-03-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extrait_mariage", "0003_alter_extraitmariage_options_demandemariage"),
    ]

    operations = [
        migrations.AddField(
            model_name="demandemariage",
            name="lieu_mariage",
            field=models.CharField(
                choices=[
                    ("municipality", "Salle de la Municipalité / قاعة البلدية"),
                    ("private", "Lieu Privé / مكان خاص"),
                ],
                default="municipality",
                max_length=20,
                verbose_name="Lieu du mariage",
            ),
        ),
        migrations.AddField(
            model_name="demandemariage",
            name="type_contrat",
            field=models.CharField(
                choices=[
                    ("municipal", "Municipal / بلدي"),
                    ("notaire", "Notaire / عدلي"),
                ],
                default="municipal",
                max_length=20,
                verbose_name="Type de contrat",
            ),
        ),
        migrations.AlterField(
            model_name="demandemariage",
            name="certificat_medical_epouse",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="declarations/mariage/epouse/medical/",
                verbose_name="Certificat Médical Epouse",
            ),
        ),
        migrations.AlterField(
            model_name="demandemariage",
            name="certificat_medical_epoux",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="declarations/mariage/epoux/medical/",
                verbose_name="Certificat Médical Epoux",
            ),
        ),
        migrations.AlterField(
            model_name="demandemariage",
            name="cin_recto_epouse",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="declarations/mariage/epouse/cin_recto/",
                verbose_name="CIN Epouse Recto",
            ),
        ),
        migrations.AlterField(
            model_name="demandemariage",
            name="cin_recto_epoux",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="declarations/mariage/epoux/cin_recto/",
                verbose_name="CIN Epoux Recto",
            ),
        ),
        migrations.AlterField(
            model_name="demandemariage",
            name="cin_verso_epouse",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="declarations/mariage/epouse/cin_verso/",
                verbose_name="CIN Epouse Verso",
            ),
        ),
        migrations.AlterField(
            model_name="demandemariage",
            name="cin_verso_epoux",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="declarations/mariage/epoux/cin_verso/",
                verbose_name="CIN Epoux Verso",
            ),
        ),
        migrations.AlterField(
            model_name="demandemariage",
            name="extrait_naissance_epouse",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="declarations/mariage/epouse/naissance/",
                verbose_name="Extrait Naissance Epouse",
            ),
        ),
        migrations.AlterField(
            model_name="demandemariage",
            name="extrait_naissance_epoux",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="declarations/mariage/epoux/naissance/",
                verbose_name="Extrait Naissance Epoux",
            ),
        ),
    ]
