# Generated by Django 6.0.2 on 2026-03-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extrait_mariage", "0004_demandemariage_lieu_mariage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="demandemariage",
            name="contrat_recu_scan",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="declarations/mariage/agent/contrats/",
                verbose_name="Scan du contrat reçu (Côté Agent)",
            ),
        ),
        migrations.AddField(
            model_name="extraitmariage",
            name="contrat_scan",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="extraits_mariage/contrats/",
                verbose_name="Scan du contrat",
            ),
        ),
        migrations.AddField(
            model_name="extraitmariage",
            name="type_acte",
            field=models.CharField(
                choices=[
                    ("municipal", "Acte Municipal / عقد بلدي"),
                    ("notarial", "Acte Notarié (Adouls) / عقد عدلي"),
                ],
                default="municipal",
                max_length=20,
                verbose_name="Type d'acte",
            ),
        ),
    ]
