# Generated by Django 6.0.2 on 2026-03-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extrait_mariage", "0005_demandemariage_contrat_recu_scan_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demandemariage",
            name="type_contrat",
            field=models.CharField(
                choices=[
                    ("municipal ", " Municipal / بلدي"),
                    ("notaire", "Notaire / عدلي"),
                ],
                default="municipal",
                max_length=20,
                verbose_name="Type de contrat",
            ),
        ),
    ]
