# Generated by Django 6.0.2 on 2026-03-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extrait_mariage", "0007_manual_column_fix"),
    ]

    operations = [
        migrations.AddField(
            model_name="extraitmariage",
            name="is_paid",
            field=models.BooleanField(default=False, verbose_name="Payé"),
        ),
    ]
