# Generated by Django 6.0.2 on 2026-04-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrait_mariage', '0008_extraitmariage_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandemariage',
            name='type_contrat',
            field=models.CharField(choices=[('municipal', 'Municipal / بلدي'), ('notaire', 'Notaire / عدلي')], default='municipal', max_length=20, verbose_name='Type de contrat'),
        ),
    ]
