# Generated by Django 6.0.2 on 2026-04-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extrait_mariage", "0010_extraitmariage_paid_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="demandemariage",
            name="is_paid",
            field=models.BooleanField(default=False, verbose_name="Payé"),
        ),
        migrations.AddField(
            model_name="demandemariage",
            name="paid_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date du paiement"
            ),
        ),
    ]
