# Generated by Django 6.0.2 on 2026-03-30 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DemandeLivretFamille",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom_chef_famille",
                    models.CharField(
                        max_length=100, verbose_name="Nom du chef de famille"
                    ),
                ),
                (
                    "prenom_chef_famille",
                    models.CharField(
                        max_length=100, verbose_name="Prénom du chef de famille"
                    ),
                ),
                (
                    "motif_demande",
                    models.CharField(
                        choices=[
                            ("premier_livret", "Premier livret"),
                            ("renouvellement", "Renouvellement"),
                            ("duplicata", "Duplicata / Nègre"),
                        ],
                        default="premier_livret",
                        max_length=50,
                        verbose_name="Motif de la demande",
                    ),
                ),
                (
                    "photo_chef_famille",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="declarations/livret/photos/",
                        verbose_name="Photo du chef de famille (facultative)",
                    ),
                ),
                (
                    "extrait_mariage",
                    models.FileField(upload_to="declarations/livret/mariage/"),
                ),
                (
                    "extrait_naissance_epoux1",
                    models.FileField(upload_to="declarations/livret/naissance_1/"),
                ),
                (
                    "extrait_naissance_epoux2",
                    models.FileField(upload_to="declarations/livret/naissance_2/"),
                ),
                (
                    "extraits_enfants",
                    models.FileField(
                        blank=True, null=True, upload_to="declarations/livret/enfants/"
                    ),
                ),
                (
                    "extrait_deces_epoux",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="declarations/livret/deces_epoux/",
                    ),
                ),
                (
                    "jugement_divorce",
                    models.FileField(
                        blank=True, null=True, upload_to="declarations/livret/divorce/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("approved", "Approuvée"),
                            ("rejected", "Rejetée"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "commentaire_agent",
                    models.TextField(blank=True, verbose_name="Commentaire de agent"),
                ),
                (
                    "issued_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="certificates/livret/issued/",
                        verbose_name="Livret prêt ou Quittance",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "citizen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demandes_livret",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande de Livret de Famille",
                "verbose_name_plural": "Demandes de Livret de Famille",
                "ordering": ["-created_at"],
            },
        ),
    ]
