# Generated by Django 6.0.2 on 2026-03-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livret_famille", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="demandelivretfamille",
            name="cin_epouse",
            field=models.CharField(
                blank=True, max_length=8, null=True, verbose_name="CIN de l'épouse"
            ),
        ),
        migrations.AddField(
            model_name="demandelivretfamille",
            name="cin_epoux",
            field=models.CharField(
                blank=True, max_length=8, null=True, verbose_name="CIN de l'époux"
            ),
        ),
        migrations.AddField(
            model_name="demandelivretfamille",
            name="etat_livret",
            field=models.CharField(
                choices=[
                    ("actif", "Actif"),
                    ("divorce", "Divorce"),
                    ("deces", "Décès d'un conjoint"),
                ],
                default="actif",
                max_length=20,
                verbose_name="État du Livret de Famille",
            ),
        ),
    ]
