# Generated by Django 6.0.2 on 2026-03-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livret_famille", "0002_demandelivretfamille_cin_epouse_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="demandelivretfamille",
            name="guichet_recuperation",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Guichet de récupération",
            ),
        ),
        migrations.AlterField(
            model_name="demandelivretfamille",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("approved", "Approuvée"),
                    ("rejected", "Rejetée"),
                    ("ready", "Prêt pour retrait"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
