# Generated by Django 6.0.2 on 2026-03-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livret_famille", "0003_demandelivretfamille_guichet_recuperation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="demandelivretfamille",
            name="is_paid",
            field=models.BooleanField(default=False, verbose_name="Paiement Reçu"),
        ),
        migrations.AlterField(
            model_name="demandelivretfamille",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("in_progress", "En cours"),
                    ("approved", "Approuvée"),
                    ("rejected", "Rejetée"),
                    ("ready", "Prêt pour retrait"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
