# Generated by Django 6.0.2 on 2026-03-18 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Citoyen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "n_etat_civil",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="N° État Civil"
                    ),
                ),
                (
                    "cin",
                    models.CharField(
                        blank=True,
                        max_length=8,
                        null=True,
                        unique=True,
                        verbose_name="CIN",
                    ),
                ),
                (
                    "prenom_ar",
                    models.CharField(max_length=100, verbose_name="Prénom AR"),
                ),
                (
                    "prenom_fr",
                    models.CharField(max_length=100, verbose_name="Prénom FR"),
                ),
                ("nom_ar", models.CharField(max_length=100, verbose_name="Nom AR")),
                ("nom_fr", models.CharField(max_length=100, verbose_name="Nom FR")),
                ("date_naissance", models.DateField(verbose_name="Date de naissance")),
                (
                    "date_naissance_lettres_ar",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Date en lettres AR"
                    ),
                ),
                (
                    "date_naissance_lettres_fr",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Date en lettres FR"
                    ),
                ),
                (
                    "lieu_naissance_ar",
                    models.CharField(
                        max_length=200, verbose_name="Lieu de naissance AR"
                    ),
                ),
                (
                    "lieu_naissance_fr",
                    models.CharField(
                        max_length=200, verbose_name="Lieu de naissance FR"
                    ),
                ),
                (
                    "sexe",
                    models.CharField(
                        choices=[("M", "M/ذكر"), ("F", "F/أنثى")],
                        max_length=10,
                        verbose_name="Sexe",
                    ),
                ),
                (
                    "profession_ar",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Profession AR",
                    ),
                ),
                (
                    "profession_fr",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Profession FR",
                    ),
                ),
                (
                    "nationalite_ar",
                    models.CharField(
                        default="تونسية", max_length=50, verbose_name="Nationalité AR"
                    ),
                ),
                (
                    "nationalite_fr",
                    models.CharField(
                        default="Tunisienne",
                        max_length=50,
                        verbose_name="Nationalité FR",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mere",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enfants_mere",
                        to="extrait_naissance.citoyen",
                        verbose_name="Mère",
                    ),
                ),
                (
                    "pere",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enfants_pere",
                        to="extrait_naissance.citoyen",
                        verbose_name="Père",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExtraitNaissance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "arrondissement_gauche",
                    models.CharField(
                        blank=True,
                        default="K/Kelibia",
                        max_length=100,
                        verbose_name="Arrondissement Document",
                    ),
                ),
                ("annee_acte", models.IntegerField(verbose_name="Année de l'acte")),
                (
                    "numero_registre",
                    models.CharField(max_length=50, verbose_name="N° Registre"),
                ),
                (
                    "declaration",
                    models.BooleanField(default=False, verbose_name="Déclaration"),
                ),
                (
                    "jugement",
                    models.BooleanField(default=False, verbose_name="Jugement"),
                ),
                (
                    "gouvernorat_ar",
                    models.CharField(
                        default="نابل", max_length=100, verbose_name="Gouvernorat AR"
                    ),
                ),
                (
                    "gouvernorat_fr",
                    models.CharField(
                        default="Nabeul", max_length=100, verbose_name="Gouvernorat FR"
                    ),
                ),
                (
                    "delegation_ar",
                    models.CharField(
                        default="قليبية", max_length=100, verbose_name="Délégation AR"
                    ),
                ),
                (
                    "delegation_fr",
                    models.CharField(
                        default="Kelibia", max_length=100, verbose_name="Délégation FR"
                    ),
                ),
                (
                    "commune_ar",
                    models.CharField(
                        default="قليبية", max_length=100, verbose_name="Commune AR"
                    ),
                ),
                (
                    "commune_fr",
                    models.CharField(
                        default="Kelibia", max_length=100, verbose_name="Commune FR"
                    ),
                ),
                (
                    "arrondissement_municipal_ar",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Arrondissement Municipal AR",
                    ),
                ),
                (
                    "arrondissement_municipal_fr",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Arrondissement Municipal FR",
                    ),
                ),
                (
                    "imada_ar",
                    models.CharField(
                        default="", max_length=100, verbose_name="Imada AR"
                    ),
                ),
                (
                    "imada_fr",
                    models.CharField(
                        default="", max_length=100, verbose_name="Imada FR"
                    ),
                ),
                (
                    "date_declaration",
                    models.DateTimeField(verbose_name="Date de déclaration"),
                ),
                (
                    "declarant_ar",
                    models.CharField(
                        default="", max_length=200, verbose_name="Déclarant AR"
                    ),
                ),
                (
                    "declarant_fr",
                    models.CharField(
                        default="", max_length=200, verbose_name="Déclarant FR"
                    ),
                ),
                (
                    "officer_etat_civil_ar",
                    models.CharField(
                        default="",
                        max_length=200,
                        verbose_name="Officier État Civil AR",
                    ),
                ),
                (
                    "officer_etat_civil_fr",
                    models.CharField(
                        default="",
                        max_length=200,
                        verbose_name="Officier État Civil FR",
                    ),
                ),
                (
                    "observations_ar",
                    models.TextField(
                        blank=True, default="", verbose_name="Observations AR"
                    ),
                ),
                (
                    "observations_fr",
                    models.TextField(
                        blank=True, default="", verbose_name="Observations FR"
                    ),
                ),
                (
                    "numero_ordre",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Numéro d'ordre",
                    ),
                ),
                (
                    "prix",
                    models.DecimalField(
                        decimal_places=3, default=0.5, max_digits=6, verbose_name="Prix"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "titulaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extraits_naissance",
                        to="extrait_naissance.citoyen",
                        verbose_name="Titulaire de l'acte",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="extraits_naissance",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur du portail",
                    ),
                ),
            ],
            options={
                "verbose_name": "Extrait de Naissance",
                "verbose_name_plural": "Extraits de Naissance",
                "ordering": ["-annee_acte", "-created_at"],
            },
        ),
    ]
