# Generated by Django 6.0.2 on 2026-03-20 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extrait_naissance", "0002_extraitnaissance_uuid"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="extraitnaissance",
            options={},
        ),
        migrations.CreateModel(
            name="DeclarationNaissance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prenom_ar",
                    models.CharField(max_length=100, verbose_name="Prénom AR"),
                ),
                (
                    "prenom_fr",
                    models.CharField(max_length=100, verbose_name="Prénom FR"),
                ),
                ("nom_ar", models.CharField(max_length=100, verbose_name="Nom AR")),
                ("nom_fr", models.CharField(max_length=100, verbose_name="Nom FR")),
                (
                    "date_naissance",
                    models.DateTimeField(verbose_name="Date et heure de naissance"),
                ),
                (
                    "lieu_naissance_ar",
                    models.CharField(
                        max_length=200, verbose_name="Lieu de naissance AR"
                    ),
                ),
                (
                    "lieu_naissance_fr",
                    models.CharField(
                        max_length=200, verbose_name="Lieu de naissance FR"
                    ),
                ),
                (
                    "sexe",
                    models.CharField(
                        choices=[("M", "M/ذكر"), ("F", "F/أنثى")],
                        max_length=10,
                        verbose_name="Sexe",
                    ),
                ),
                (
                    "cin_pere",
                    models.CharField(
                        blank=True, max_length=8, null=True, verbose_name="CIN Père"
                    ),
                ),
                (
                    "cin_mere",
                    models.CharField(
                        blank=True, max_length=8, null=True, verbose_name="CIN Mère"
                    ),
                ),
                (
                    "commentaire",
                    models.TextField(blank=True, verbose_name="Commentaire / ملاحظات"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente / قيد الانتظار"),
                            ("validated", "Validé / تم التحقق"),
                            ("rejected", "Rejeté / مرفوض"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "declarant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="declarations_naissance",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Déclarant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Déclaration de Naissance",
                "verbose_name_plural": "Déclarations de Naissance",
            },
        ),
    ]
