# Generated by Django 6.0.2 on 2026-03-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "extrait_naissance",
            "0003_alter_extraitnaissance_options_declarationnaissance",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="HospitalBirthRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cert_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="N° Certificat Hôpital"
                    ),
                ),
                ("hospital_name", models.CharField(max_length=200)),
                ("date_naissance", models.DateTimeField()),
                (
                    "sexe",
                    models.CharField(
                        choices=[("M", "M/ذكر"), ("F", "F/أنثى")], max_length=10
                    ),
                ),
                ("cin_mere", models.CharField(max_length=8)),
                ("cin_pere", models.CharField(blank=True, max_length=8, null=True)),
                (
                    "is_used",
                    models.BooleanField(
                        default=False, verbose_name="Déjà utilisé pour une déclaration"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="declarationnaissance",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="declarations/naissance/",
                verbose_name="Pièce jointe (Scan)",
            ),
        ),
        migrations.AddField(
            model_name="declarationnaissance",
            name="hospital_cert_number",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="N° Certificat Hôpital",
            ),
        ),
    ]
