# Generated by Django 6.0.2 on 2026-03-20 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "extrait_naissance",
            "0004_hospitalbirthrecord_declarationnaissance_attachment_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="HospitalBirthRecord",
        ),
        migrations.RemoveField(
            model_name="declarationnaissance",
            name="hospital_cert_number",
        ),
    ]
