# Generated by Django 6.0.2 on 2026-03-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extrait_naissance", "0005_delete_hospitalbirthrecord_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="declarationnaissance",
            name="cin_mere_scan",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="declarations/naissance/parents/mere/",
                verbose_name="Scan CIN Mère",
            ),
        ),
        migrations.AddField(
            model_name="declarationnaissance",
            name="cin_pere_scan",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="declarations/naissance/parents/pere/",
                verbose_name="Scan CIN Père",
            ),
        ),
        migrations.AddField(
            model_name="declarationnaissance",
            name="signature_declarant",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="declarations/naissance/signatures/",
                verbose_name="Signature du déclarant",
            ),
        ),
    ]
