# Generated by Django 6.0.2 on 2026-03-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extrait_naissance", "0006_declarationnaissance_cin_mere_scan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="extraitnaissance",
            name="is_paid",
            field=models.BooleanField(default=False, verbose_name="Payé"),
        ),
    ]
