# Generated by Django 6.0.2 on 2026-04-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extrait_naissance", "0007_extraitnaissance_is_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="extraitnaissance",
            name="paid_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date du paiement"
            ),
        ),
    ]
