# Generated by Django 6.0.2 on 2026-04-22 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extrait_naissance", "0008_extraitnaissance_paid_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DemandeLegalisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_document",
                    models.CharField(max_length=200, verbose_name="Type de document"),
                ),
                (
                    "nombre_copies",
                    models.IntegerField(default=1, verbose_name="Nombre de copies"),
                ),
                ("motif", models.TextField(blank=True, verbose_name="Motif / Usage")),
                ("is_paid", models.BooleanField(default=False, verbose_name="Payé")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente / قيد الانتظار"),
                            ("paid", "Payé / تم الدفع"),
                            ("completed", "Signé / تم الإمضاء"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "citizen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demandes_legalisation",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Demandeur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande de légalisation",
                "verbose_name_plural": "Demandes de légalisation",
            },
        ),
    ]
