# Generated by Django 6.0.2 on 2026-04-01 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeEvenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_evenement', models.CharField(max_length=200, verbose_name="Intitulé de l'événement")),
                ('type_evenement', models.CharField(choices=[('fete_familiale', 'Fête familiale / حفل عائلي'), ('concert', 'Concert / حفلة موسيقية'), ('marche', 'Marché / سوق'), ('association', 'Activité associative / نشاط جمعوي'), ('sportif', 'Événement sportif / حدث رياضي'), ('culturel', 'Événement culturel / حدث ثقافي'), ('commercial', 'Événement commercial / حدث تجاري'), ('autre', 'Autre / أخرى')], default='autre', max_length=30, verbose_name="Type d'événement")),
                ('description', models.TextField(verbose_name="Description de l'événement")),
                ('nombre_participants', models.PositiveIntegerField(verbose_name='Nombre estimé de participants')),
                ('lieu_type', models.CharField(choices=[('espace_public', 'Espace public (rue, place) / فضاء عمومي'), ('salle_fetes', 'Salle des fêtes municipale / قاعة الأفراح البلدية'), ('stade', 'Stade / ملعب'), ('plage', 'Plage / شاطئ'), ('domicile_prive', 'Domicile privé / منزل خاص'), ('autre', 'Autre lieu / مكان آخر')], default='espace_public', max_length=30, verbose_name='Type de lieu')),
                ('lieu_details', models.CharField(max_length=300, verbose_name='Adresse / Précisions sur le lieu')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('heure_debut', models.TimeField(verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(verbose_name='Heure de fin')),
                ('nom_organisateur', models.CharField(max_length=200, verbose_name="Nom complet de l'organisateur")),
                ('cin_organisateur', models.CharField(max_length=8, verbose_name="CIN de l'organisateur")),
                ('telephone_organisateur', models.CharField(max_length=20, verbose_name="Téléphone de l'organisateur")),
                ('association_nom', models.CharField(blank=True, max_length=200, null=True, verbose_name="Nom de l'association")),
                ('cin_recto', models.ImageField(blank=True, null=True, upload_to='declarations/evenements/cin_recto/', verbose_name='CIN Recto')),
                ('cin_verso', models.ImageField(blank=True, null=True, upload_to='declarations/evenements/cin_verso/', verbose_name='CIN Verso')),
                ('plan_lieu', models.FileField(blank=True, null=True, upload_to='declarations/evenements/plan/', verbose_name='Plan / Carte du lieu')),
                ('programme_evenement', models.FileField(blank=True, null=True, upload_to='declarations/evenements/programme/', verbose_name="Programme de l'événement")),
                ('attestation_assurance', models.FileField(blank=True, null=True, upload_to='declarations/evenements/assurance/', verbose_name="Attestation d'assurance")),
                ('plan_securite', models.FileField(blank=True, null=True, upload_to='declarations/evenements/securite/', verbose_name='Plan de sécurité')),
                ('attestation_association', models.FileField(blank=True, null=True, upload_to='declarations/evenements/association/', verbose_name="Attestation d'enregistrement de l'association")),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours de traitement'), ('approved', 'Autorisée'), ('rejected', 'Rejetée')], default='pending', max_length=20, verbose_name='Statut')),
                ('commentaire_agent', models.TextField(blank=True, verbose_name="Commentaire de l'agent")),
                ('autorisation_signee', models.FileField(blank=True, null=True, upload_to='autorisations/evenements/', verbose_name='Autorisation signée')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Frais de dossier réglés')),
                ('has_conflict', models.BooleanField(default=False, verbose_name='Conflit détecté')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_evenement', to=settings.AUTH_USER_MODEL, verbose_name='Demandeur')),
                ('conflict_with', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflicting_requests', to='social_evenements.demandeevenement', verbose_name='En conflit avec')),
            ],
            options={
                'verbose_name': "Demande d'autorisation d'événement",
                'verbose_name_plural': "Demandes d'autorisation d'événements",
                'ordering': ['-created_at'],
            },
        ),
    ]
