# Generated by Django 6.0.2 on 2026-04-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_evenements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeevenement',
            name='type_evenement_libre',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name="Type d'événement (précision libre)"),
        ),
        migrations.AlterField(
            model_name='demandeevenement',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours de traitement'), ('approved', 'Autorisée'), ('rejected', 'Rejetée'), ('changes_requested', 'Modifications demandées')], default='pending', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='demandeevenement',
            name='type_evenement',
            field=models.CharField(choices=[('fete_familiale', 'Fête familiale / حفل عائلي'), ('mariage', 'Cérémonie de mariage / حفل زفاف'), ('remise_diplomes', 'Remise de diplômes / حفل التخرج'), ('concert', 'Concert / حفلة موسيقية'), ('marche', 'Marché / سوق'), ('association', 'Activité associative / نشاط جمعوي'), ('sportif', 'Événement sportif / حدث رياضي'), ('culturel', 'Événement culturel / حدث ثقافي'), ('commercial', 'Événement commercial / حدث تجاري'), ('religieux', 'Événement religieux / تظاهرة دينية'), ('politique', 'Réunion / Meeting politique / تجمع سياسي'), ('charite', 'Événement caritatif / نشاط خيري'), ('autre', 'Autre (préciser) / أخرى (تحديد)')], default='autre', max_length=30, verbose_name="Type d'événement"),
        ),
    ]
