# Generated by Django 6.0.2 on 2026-04-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_evenements", "0002_add_type_libre_and_changes_requested_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="demandeevenement",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
