# Generated by Django 6.0.2 on 2026-04-18 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeCommerce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('licence_enseigne', "Licence d'installation d'une enseigne publicitaire")], max_length=40, verbose_name='Type de service')),
                ('nom_commerce', models.CharField(max_length=200, verbose_name='Nom du commerce')),
                ('adresse_commerce', models.TextField(verbose_name='Adresse du commerce')),
                ('description', models.TextField(blank=True, verbose_name='Description / Détails')),
                ('cin_recto', models.ImageField(blank=True, null=True, upload_to='declarations/commerce/cin_recto/')),
                ('cin_verso', models.ImageField(blank=True, null=True, upload_to='declarations/commerce/cin_verso/')),
                ('photo_enseigne', models.ImageField(blank=True, null=True, upload_to='declarations/commerce/enseignes/', verbose_name="Photo de l'enseigne (optionnel)")),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('approved', 'Approuvée'), ('rejected', 'Rejetée')], default='pending', max_length=20)),
                ('is_paid', models.BooleanField(default=False, verbose_name='Paiement reçu')),
                ('commentaire_agent', models.TextField(blank=True)),
                ('issued_document', models.FileField(blank=True, null=True, upload_to='certificates/commerce/issued/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_commerce', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande Boutiques & Commerces',
                'verbose_name_plural': 'Demandes Boutiques & Commerces',
                'ordering': ['-created_at'],
            },
        ),
    ]
