# Generated by Django 6.0.2 on 2026-04-18 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeImpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('enregistrement_bien', "Enregistrement d'un bien (Rez-de-chaussée, étage, garage)"), ('changement_propriete', 'Changement de propriété (Achat ou héritage)'), ('changement_vocation', 'Changement de vocation (Logement en commerce, etc.)'), ('arret_activite', "Déclaration d'arrêt d'activité (Fermer une boutique)"), ('certificat_imposition', "Certificat d'inscription au rôle d'imposition")], max_length=40, verbose_name='Type de service')),
                ('adresse_bien', models.TextField(verbose_name='Adresse du bien / local')),
                ('description', models.TextField(blank=True, verbose_name='Description / Détails')),
                ('cin_recto', models.ImageField(blank=True, null=True, upload_to='declarations/impots/cin_recto/')),
                ('cin_verso', models.ImageField(blank=True, null=True, upload_to='declarations/impots/cin_verso/')),
                ('document_propriete', models.FileField(blank=True, null=True, upload_to='declarations/impots/documents/', verbose_name='Document de propriété (optionnel)')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('approved', 'Approuvée'), ('rejected', 'Rejetée')], default='pending', max_length=20)),
                ('is_paid', models.BooleanField(default=False, verbose_name='Paiement reçu')),
                ('commentaire_agent', models.TextField(blank=True)),
                ('issued_document', models.FileField(blank=True, null=True, upload_to='certificates/impots/issued/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_impot', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande Argent & Impôts',
                'verbose_name_plural': 'Demandes Argent & Impôts',
                'ordering': ['-created_at'],
            },
        ),
    ]
