# Generated by Django 6.0.2 on 2026-03-26 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DemandeResidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "adresse_demandee",
                    models.TextField(verbose_name="Adresse du domicile à Kélibia"),
                ),
                (
                    "cin_copy",
                    models.FileField(
                        upload_to="declarations/residence/cin/",
                        verbose_name="Copie de la CIN",
                    ),
                ),
                (
                    "quitus_municipal",
                    models.FileField(
                        upload_to="declarations/residence/quitus/",
                        verbose_name="Attestation de décharge (Quitus)",
                    ),
                ),
                (
                    "acte_deces_conjoint",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="declarations/residence/deces/",
                        verbose_name="Copie de l'acte de décès (si applicable)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("approved", "Approuvée"),
                            ("rejected", "Rejetée"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "issued_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="certificates/residence/issued/",
                        verbose_name="Attestation signée (Papier)",
                    ),
                ),
                (
                    "commentaire_agent",
                    models.TextField(blank=True, verbose_name="Commentaire de l'agent"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "citizen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demandes_residence",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande d'Attestation de Résidence",
                "verbose_name_plural": "Demandes d'Attestation de Résidence",
                "ordering": ["-created_at"],
            },
        ),
    ]
