# Generated by Django 6.0.2 on 2026-03-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attestation_residence", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="demanderesidence",
            name="cin_recto",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="declarations/residence/cin_recto/",
                verbose_name="CIN Recto",
            ),
        ),
        migrations.AddField(
            model_name="demanderesidence",
            name="cin_verso",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="declarations/residence/cin_verso/",
                verbose_name="CIN Verso",
            ),
        ),
        migrations.AddField(
            model_name="demanderesidence",
            name="motif_demande",
            field=models.TextField(
                blank=True, null=True, verbose_name="Motif de la demande"
            ),
        ),
        migrations.AddField(
            model_name="demanderesidence",
            name="profession",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Profession"
            ),
        ),
        migrations.AddField(
            model_name="demanderesidence",
            name="telephone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="N° de téléphone"
            ),
        ),
        migrations.AlterField(
            model_name="demanderesidence",
            name="cin_copy",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="declarations/residence/cin/",
                verbose_name="Copie de la CIN (Fichier unique)",
            ),
        ),
        migrations.AlterField(
            model_name="demanderesidence",
            name="quitus_municipal",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="declarations/residence/quitus/",
                verbose_name="Attestation de décharge (Quitus)",
            ),
        ),
    ]
