# Generated by Django 6.0.2 on 2026-04-21 10:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attestation_residence", "0003_demanderesidence_is_paid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="demanderesidence",
            name="cin",
            field=models.CharField(
                blank=True,
                max_length=8,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{8}$", "Ce champ doit contenir exactement 8 chiffres."
                    )
                ],
                verbose_name="N° de CIN",
            ),
        ),
        migrations.AlterField(
            model_name="demanderesidence",
            name="telephone",
            field=models.CharField(
                blank=True,
                max_length=8,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{8}$", "Ce champ doit contenir exactement 8 chiffres."
                    )
                ],
                verbose_name="N° de téléphone",
            ),
        ),
    ]
